<?php

/**
 * Jornada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Jornada extends BaseJornada
{
    public static function obtenerPartidosDeUnaJornada($idJornada)
    {
        $query = Doctrine_Query::create()->from('Partido')->where('idJornada = ' . $idJornada);
        return $query->execute();
    }
}