<?php

/**
 * Liga
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Liga extends BaseLiga
{
    public static function obtenerLigaPorId($idLiga)
    {
        $query = Doctrine_Query::create()->from('Liga')->where('id = ' . $idLiga);
        return $query->execute()->getFirst();
    }

    public static function obtenerUltimoTorneoDeUnaLiga($idLiga)
    {
        $query = Doctrine_Query::create()->from('Torneo')->where('idLiga = ' . $idLiga)->orderBy('id DESC')->limit('0, 1');
        return $query->execute()->getFirst();
    }

    public static function obtenerNumeroDeSeguidores($idLiga)
    {
        $query = Doctrine_Query::create()->select('SUM(idUsuario) AS total')->from('UsuarioLigaSeguida')->where('idLiga = ' . $idLiga);
        return $query->execute()->getFirst();
    }
}