<?php

/**
 * Torneo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Torneo extends BaseTorneo
{
    public static function obtenerAvisosDeUnTorneo($idTorneo)
    {
        $query = Doctrine_Query::create()->from('Aviso')->where('idTorneo = ' . $idTorneo);
        return $query->execute();
    }

    public static function obtenerEquiposDeUnTorneo($idTorneo)
    {
        $query = Doctrine_Query::create()->from('Equipo')->where('idTorneo = ' . $idTorneo);
        return $query->execute();
    }

    public static function obtenerJornadasDeUnTorneo($idTorneo)
    {
        $query = Doctrine_Query::create()->from('Jornada')->where('idTorneo = ' . $idTorneo);
        return $query->execute();
    }
}